global_requirements.fish

If the global_requirements is used to keep the package updated,
for example the pip and setuptools, only install the packages
will not work.

Install/Upgrade global_requirements

---

README.mdown
docs/index.rst
docs/usage.rst
virtual.fish

- Add help subcommand for convenience/consistency 
with other tools
- Make the --description text of all functions consistent and 
under 80 char wide so that the help display looks nice
- Sort alphabetically the docs/usage.rst commands and make 
references to 'currently-activated virtualenv' consistent
Address part of Issue #40 (most of it was already addressed :+1:  )

feat(toplevel): add vf help subcommand + improve documentation consistency/look

---

docs/plugins.rst

'exec' didn't work for me, but 'eval' did

change documentation about to executing plugins in config.fish

---

docs/plugins.rst

Just adding in the plugin names explicitly in the docs to help clarify the name that needs to be passed in to the loader line.

Explicitly list the names of plugins

---

docs/plugins.rst
virtualfish/projects.fish

This pull request includes two commits:
* docs(plugins): add description for the `vf lsprojects` command
* feat(projects plugin): add the `vf cdproject` command
This command searches for a project matching the name of the currently
activated virtualenv. If found, it switches to the respective project
directory. If `VIRTUALFISH_COMPAT_ALIASES` is set, `cdproject` is
aliased to this command.
For more information:
http://virtualenvwrapper.readthedocs.org/en/latest/command_ref.html#cdproject
Please review and comment.

Improvements to the projects plugin

---

docs/usage.rst

Fix the documentation's reST syntax. I think the `readthedocs` should be updated too. I guess I love documentation :).

docs(usage): fix rst for list of commands

---

docs/plugins.rst
virtualfish/compat_aliases.fish

Quoting [lsvirtualenv](http://virtualenvwrapper.readthedocs.org/en/latest/command_ref.html#lsvirtualenv)'s command reference:
> **lsvirtualenv**
> 
> List all of the environments.

feat(compat_aliases): add missing `lsvirtualenv`

---

virtualfish/__main__.py

`inspect.getfile(inspect.currentframe())` seems to return a relative path that
ends up with the virtualfish functions not being loaded.
Fixes #76 
After this fix:
```
nick@cumulus /> python2.7 -m virtualfish
. /usr/local/lib/python2.7/site-packages/virtualfish-1.0.0-py2.7.egg/virtualfish/virtual.fish;emit virtualfish_did_setup_plugins
nick@cumulus /> python3.5 -m virtualfish
. /usr/local/lib/python3.5/site-packages/virtualfish-1.0.0-py3.5.egg/virtualfish/virtual.fish;emit virtualfish_did_setup_plugins
```

Use __file__ to find find the module

---

docs/seealso.rst

a "space" was needed before the angled bracket.

Fixed the syntax for URL to the oh-my-fish

---

docs/plugins.rst
virtualfish/environment.fish

Add environment plugin and documentation
This is built largely on the existing work of shanx in https://github.com/adambrenecki/virtualfish/pull/39 and the ideas in #92 by adambreneck. This should address #92 and my manual testing was successful. Please let me know if there are any improvements that I can make.

Add environment plugin

---

virtualfish/virtual.fish

```console
$ vf 
virtualfish 1.0.5
Usage: vf <command> [<args>]
Available commands:
activate        # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 44
addpath         # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 204
all             # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 241
cd              # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 177
cdpackages      # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 185
connect         # Defined in /home/joar/.local/lib/python3.5/site-packages/virtualfish/virtual.fish @ line 275
deactivate      # Defined in …
```

Fix subcommand helptext

---

virtualfish/__main__.py
virtualfish/virtual.fish

I want to keep my shell configuration in a git repository, and avoid manual installation steps as much as possible.
I store 'virtualenv' and 'virtualfish' as git submodules. 'virtualenv' works just fine when PYTHONPATH points to its repository. The only problem is 'virtualfish' requiring installation, just to show version information.

Make virtualfish work without installation

---

docs/plugins.rst
virtualfish/projects.fish

Includes fix from @dwt for project completions when `PROJECT_HOME` is not set or available. See also: https://github.com/adambrenecki/virtualfish/pull/134

Add preliminary support for .project files

---

docs/plugins.rst

The purpose of this change is to help users understand how to get
workon` behaving similar to virtualenvwrapper's `workon` when the
`compat_aliases` and `projects` plugins are used together.
- The `compat_aliases` plug-in aliases `workon` to `vf activate`.
- The `project` plugin aliases `workon` to `vf workon`, but only
when `VIRTUALFISH_COMPAT_ALIASES` is set when the plug-in is
loaded.
So the order the two plugins are listed (i.e., loaded) matters,
and so does whether or not the VIRTUALFISH_COMPAT_ALIASES environment
variable is set.
If VIRTUALFISH_COMPAT_ALIASES is not set before the projects plugin is
loaded or the compat_aliases is loaded after the project plugin then
`workon` will activate the virtual environtment, but will not
automatically change to the  project directory.
See …

Document workon alias behavior with Projects plugin

---

setup.py

Otherwise results in:
```
AttributeError: 'Function' object has no attribute 'get_closest_marker'
```
See also: https://github.com/pytest-dev/pytest-asyncio/issues/115

Update minimum PyTest version

---

virtualfish/test/repl.py

I noticed that running the tests currently results in a test failure due to a TypeError in the REPL test code's `run()` function:
```
TypeError: write() argument must be str, not bytes
```
I don't know whether it is an appropriate fix, but I resolved the error by converting the output bytes to strings.

Fix TypeError in Fish REPL test run() function

---

virtualfish/virtual.fish

Using multiple `cd` calls means one cannot use `cd -` to return to the previous directory. (#95)
`vf globalpackages` isn't supposed to change directory, so it should use `pushd`/`popd` instead (#108)

Avoid using cd unnecessarily

---

virtualfish/virtual.fish

Sometimes the 'functions' command outputs the function definition
location (file and line number) as a comment before the actual function
definition. When that happens, the help text would be set to the comment
instead of to the function description.
This greps for the first line starting with the word 'function' to find
the help text.

Fix autocomplete help text when 'functions' prints comments.

---

docs/install.rst
docs/usage.rst
virtualfish/virtual.fish

This adds argument parsing to the `vf new` command (#71) via Fish's [`argparse` function](https://fishshell.com/docs/current/cmds/argparse.html), which I then subsequently used to provide the following enhancements:
* Find & use non-PATH Python interpreters via common paths/tools (Pyenv, Pythonz, etc.) (#114)
* Virtual environment name no longer needs to be passed as last argument (#16)
* Control output verbosity via `--quiet`, `--verbose`, & `--debug` flags
* Add help via `vf new --help` option flag (#146)

feat(new): Parse args, support Pyenv & much more

---

README.md
RELEASE.md
pyproject.toml
virtualfish/loader/cli.py
virtualfish/virtual.fish

Certain VirtualFish functionality depends on newer Fish shell features. Users on older Fish versions who don't notice the minimum version requirement may subsequently encounter errors.
For example, "&&" is not supported on older Fish versions, so this includes a commit that switches to more-verbose but more-compatible syntax. Other parts of VirtualFish still require Fish 3.1+, but this bit was causing errors any time `virtualfish.fish` was sourced.
This also adds a prominent minimum Fish version notice to the README. This information was already available in the **Installing** docs, but some folks did not see that.
Most notably, this adds a `check_fish_version()` function to the initial Python-based installation process that exits and notifies if the minimum Fish shell version requirement …

Require minimum Fish shell version when installing

---

docs/plugins.rst
virtualfish/auto_activation.fish
virtualfish/projects.fish

The goal of this PR is to ensure that projects activated with `vf workon` are deactivated again when leaving the project's directory in cases where both the projects and the auto-activation plugins are used.
- Activating a venv and switching directory using `vf workon` now sets VF_AUTO_ACTIVATED flag if auto activation plugin is sourced
- In the auto activation plugin, check if projects plugin is sourced. If so, check if PWD is a project directory to make sure changing into project subdirectories does not deactivate venv if no activation file is present
I'm not exactly an expert in Fish and wasn't sure what's the best way to check if another plugin has been sourced. I just check if a particular function from the projects or auto-activation plugin is available using `type -q`, but please …

Make the auto activation and projects plugin play nice together

---

docs/usage.rst
virtualfish/virtual.fish

At present, the only way to understand the state of one's virtual environments is to manually activate and inspect each one. There isn't an easy way to answer the following questions about virtual environments:
* Which are using out-of-date Python versions?
* Which Python versions are they associated with?
* Are any broken? Has Homebrew busted them again?
* Add `--details` option to `vf ls` to show an additional column containing virtual environments' Python versions. 
* Detect whether environments are in working order, and if not, indicate which are broken.
* Colorize version numbers to show whether the default Python version is more up-to-date than an environment's version.

vf ls: Add --details to show virtual environment Python versions

---

docs/extend.rst
docs/plugins.rst
docs/usage.rst
virtualfish/virtual.fish

Replacing the now-deprecated `update_python` plugin, the new `vf upgrade` command can both perform in-place virtual environment upgrades as well as re-build environments from scratch, even when environment Python/Pip executables are inoperable.
See documentation within for more details. Closes #141

Add `vf upgrade` to fix outdated/broken environments

---

virtualfish/virtual.fish

Hello!
This patch implements explicit actions for `vf globalpackages` as discussed in #181. The old behavior (toggle) is preserved when calling with no explicit action. I also added a `-q/--quiet` switch to remove the new state display. Finally, reworking this was the opportunity to add a help message, following the incentive in #105.
New usage:
- `vf globalpackages [-q]`: toggle use of system site packages
- `vf globalpackages toggle [-q]`: same as above
- `vf globalpackages enable [-q]`: enable system site packages
- `vf globalpackages disable [-q]`: disable system site packages
The command returns 0 up success.
Comments most welcome. Thanks!

globalpackages: add enable/disable/toggle subcommands, add help

---

virtualfish/auto_activation.fish

I had some issues when creating Fish scripts that occasionally `cd` to venv-connected directories.
This fix should make auto-activation work only when the shell is actually interactive.

auto_activation: Auto-activate only for interactive sessions

---

RELEASE.md
docs/usage.rst
virtualfish/virtual.fish

Introduce an optional `<env name>` argument to `vf connect` which auto-activates the virtualenv in question, if it exists.

feat(connect): Auto-activate virtualenv if specified

---

virtualfish/virtual.fish

Hopefully this fixes #203.
To test if a Python version is available via Pyenv (e.g. when calling `vf new -p 3.8.10 my_venv`), VirtualFish called `pyenv which python$py_version`. However, `pyenv which python3.8.10` fails (at least in the most recent version of Pyenv) and `pyenv which python 3.8.10` seems to ignore the provided version and always prints the path of whatever Python version is currently active in Pyenv.
This fix instead checks for `$PYENV_ROOT/versions/$py_version/bin/python` OR `$HOME/.pyenv/versions/$py_version/bin/python` (if $PYENV_ROOT not set, which might for example be the case when Pyenv was installed with Homebrew). With these changes, specifying versions with just the number works again:
```fish
> pyenv versions
system
3.8.10
* 3.9.5 (set by …
```

Fix Pyenv version detection

---

docs/plugins.rst
virtualfish/virtual.fish

Currently, if my venv `project-venv` contains a `.project` file, this file is not recreated when I call `vf upgrade --rebuild project-venv`. I think it is reasonable to expect the 'rebuild' command to restore this file.

Preserve .project file when doing vf upgrade --rebuild

---

virtualfish/auto_activation.fish

This is an attempt to improve my previous pull request about making the auto-activation plugin 'project aware', so that virtualenvs of projects are automatically deactivated when leaving the project directory (#175). The solution back then was to only deactivate virtualenvs of projects automatically if they contain a `.project` file. However, this solution feels very unintuitive to me, partly because it seems against the 'intended' use of the projects plugin, which suggests to only use `.project` files if the project is not in the `$PROJECT_HOME` directory - and I like to keep all my projects in `$PROJECT_HOME`.
This patch aims to accommodate this workflow by auto-deactivating virtualenvs of projects in `$PROJECT_HOME` without needing `.project` or `.venv` files. It adds a check to the …

Auto-deactivate venvs in $PROJECT_HOME without requiring .project files

---

virtualfish/auto_activation.fish

Uff, I just realized that #209 introduced a rather unfortunate bug: when I just want to activate a venv that is not connected to any project or has an activation file ( `vf activate testvenv`), #209 will immediately deactivate the venv when changing the directory (because it's not in `$PROJECT_HOME`). To fix this, I now also check if $VIRTUAL_ENV is in `vf lsprojects`

Don't auto-deactivate venv if it's not a project

---

docs/usage.rst
virtualfish/virtual.fish

Previously, environment Python versions in the list shown by `vf ls --details` were only considered to be up-to-date (i.e., displayed in green) when a given environment's Python version is greater or equal to the default Python version returned by `__vfsupport_get_default_python()`. If you have some environments on older but fully-supported Python versions, those would show up in yellow even though they should be considered up-to-date.
With these changes, given a `~/.tool-versions` file that contains the following line:
python 3.9.7 3.8.12 3.7.11 3.6.14
… any environment's Python version that matches one of the specified versions will be considered up-to-date and displayed in green.

Use tool versions file to colorize `ls --details`

---

virtualfish/virtual.fish

Found out this was missing while rebuilding my venvs for Python 3.10.
This seems to be the only missing command.

Add completions for upgrade command

---

virtualfish/virtual.fish

We should use native virtualfish commands
`mkvirtualenv` is only available through the compat-aliases virtualfish plugin: https://virtualfish.readthedocs.io/en/latest/plugins.html#virtualenvwrapper-compatibility-aliases-compat-aliases

Suggest native `vf new` command when venv does not exist

---

virtualfish/virtual.fish

Both `vf activate myvenv` and `vf activate myvenv/` successfully activate the venv, 
but the latter causes a warning to be printed to the terminal.
Came across this because at some stage a trailing slash somehow ended up at the end of my activate command.
The trailing slash doesn't cause any issues with activation since the venv's are directories, and trailing slashes do not cause issues with the various functions (`test -d` etc) used in virtualfish when activating a venv, so for the warning message just checking the `basename` should be fine.

Avoid erroneous warning if venv activated with trailing slash

---

.pre-commit-config.yaml

Thank you for using Unimport, there was a slight change in the URL, the old URL works because it is redirected to the new one, but I changed it to the new one just in case.

Fix unimport linter repo URL

---

pyproject.toml

Also increments Sphinx-related versions, which were quite old.
Flake8 remains pinned to 3.9.x until their war with the `importlib-metadata` people has been resolved.

Remove upper bounds on most dev dependencies

---

.github/ISSUE_TEMPLATE/---bug-report.md
.pre-commit-config.yaml
RELEASE.md
pyproject.toml
virtualfish/loader/__init__.py
virtualfish/virtual.fish

Fixes #240 
Python 3.12 removed `distutils` and bundled `setuptools` (aka `pkg_resources`): https://docs.python.org/3.12/whatsnew/3.12.html#removed
Also bumps to python 3.8+ (since 3.7 is unsupported and would require a backport of `importlib.metadata`)

Replace Setuptools for Python 3.12

---

RELEASE.md
virtualfish/loader/cli.py

Use `--version` command-line option to read current fish-shell version rather than parsing assumed, configuration altered, fish command output.

Workaround for #238 regression / #245 issue
